### ISSUE TITLE
Bosch SHC: smokedetector_check not work

### ISSUE THREAD

**Issue by sashgithub** [tschamm/boschshc-hass#43]
I have trigger the service call smokedetector_check with the entity_id: binary_sensor.flur_battery of the smoke detector.
It doesn´t work yet. In The code The device ist the binary_sensor or I do something wrong?

Logger: homeassistant.helpers.script.websocket_api_script
Source: helpers/service.py:694
First occurred: 10:47:13 (1 occurrences)
Last logged: 10:47:13

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'BatterySensor' object has no attribute 'async_request_smoketest'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 381, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 584, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 691, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 896, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 694, in _handle_entity_call
    result = hass.async_run_job(partial(getattr(entity, func), **data))  # type: ignore
AttributeError: 'BatterySensor' object has no attribute 'async_request_smoketest'

**Comment by sashgithub** [comment]
The same Problem by the service call "Bosch SHC: smokedetector_alarmstate"

**Comment by tschamm** [comment]
The service is meant only for smoke detector binary sensor entities, not the battery entity of the smoke detector.

**Comment by sashgithub** [comment]
But the twinguard has only the binary sensor for battery.

**Comment by tschamm** [comment]
The twinguard is another product category at Bosch, thus services provided for smoke detectors cannot be used. Actually I'm not aware how to trigger the test alarm, or change settings of the twinguard via the API.

**Comment by sashgithub** [comment]
Okay thanx. 

I´m a beginner in programming.

This could possibly help:
Bosch Smart Home Local API for Twinguard
https://apidocs.bosch-smarthome.com/local/index.html#/States/put_devices__deviceId__services_SmokeDetectorCheck_state

**Comment by tschamm** [comment]
I double checked, the twinguard does provide the same check, however I implemented the service only for smoke detector devices. I will provide an update for this.

**Comment by HAuser2019** [comment]
Hi, would you pleaaaase add the SmokeDetector and IntrusionDetection from the Hacs intergration to the official Bosch SmartHomeController intergration in Home Assistant? It's being missed very much!
Can I buy you a coffee?

**Comment by tschamm** [comment]
I'll add the smoke detector pull request after the holidays. 
I'm sorry this takes so long, but PR reviews are lasting so long...

**Comment by timwnl** [comment]
Hi @tschamm, I have been on a quest for integrating my Bosch SHC to Home Assistant. Noticed this repository besides the 'main' repository. This repository better suits my needs, however I am still missing the smoke sensor for the twinguards. My regular 'Bosch smoke detector' does have a smoke sensor feature. Is this correct? Or a bug? 

I have noticed the SmokeDetector feature, does this feature include the twinguards IF they detect smoke? That would solve the most important feature of course.

**Comment by HAuser2019** [comment]
I'm a user: The HACS repository does support the Twinguard as smokedetector. I'm still hoping the "official" integration wil support everything soon. But it seems it's still wating for a PR :-(

**Comment by saxn-paule** [comment]
> I double checked, the twinguard does provide the same check, however I implemented the service only for smoke detector devices. I will provide an update for this.

Last week I installed a twinguard. It seems that the smoke_detector function is still missing, or did I do something wrong?

**Comment by tschamm** [comment]
You're right, I did not catch up with this yet.

**Comment by michaelhenningersrb** [comment]
Hi, anything new on this topic yet?

**Comment by MephistoJB** [comment]
May I ask for an Update regarding this topic. It would increase the benefit of the Integration dramaticly. Atm I am working with a workaround with nodered and mqtt which is a total pita to honest. Thank you.

**Comment by hippotastic** [comment]
Hello, I'd also like to express interest in getting the TwinGuard smoke detector functionality into Home Assistant. All the other sensors of the device work fine, but the smoke alarm binary sensor is missing.

**Comment by MephistoJB** [comment]
Do you have any news about this?

**Comment by Draexl** [comment]
Hi, any news? At the moment I use "iobroker" to find the correct Twinguard.

**Comment by mosandlt** [comment]
Fixed and released in [v0.4.106](https://github.com/tschamm/boschshc-hass/releases/tag/v0.4.106): the smoke-detector services now target the entity correctly. Please update via HACS and reopen if it still occurs.
